version: "3"
services:
  reverseproxy:
    image: openflocks/reverseproxy
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - backend-user
      - backend-feed
  backend-user:
    image: openflocks/udacity-restapi-user
    volumes:
      - $HOME/.aws:/root/.aws
    env_file: .env
    environment:
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DATABASE_NAME: $POSTGRES_DATABASE_NAME
      POSTGRES_HOST: $POSTGRES_HOST
      AWS_REGION: $AWS_REGION
      AWS_PROFILE: $AWS_PROFILE
      AWS_MEDIA_BUCKET: $AWS_MEDIA_BUCKET
      JWT_SECRET: $JWT_SECRET
      URL: "http://localhost:8100"
  backend-feed:
    image: openflocks/udacity-restapi-feed
    volumes:
      - $HOME/.aws:/root/.aws
    env_file: .env
    environment:
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DATABASE_NAME: $POSTGRES_DATABASE_NAME
      POSTGRES_HOST: $POSTGRES_HOST
      AWS_REGION: $AWS_REGION
      AWS_PROFILE: $AWS_PROFILE
      AWS_MEDIA_BUCKET: $AWS_MEDIA_BUCKET
      JWT_SECRET: $JWT_SECRET
      URL: "http://localhost:8100"
  frontend:
    image: openflocks/udacity-frontend
    ports:
      - "8100:80"
